kinetics400_to_interaction ={ 
  "sharpening knives": "unknown", 
  "cutting nails": "unknown", 
  "eating ice cream": "eats with",
  "changing wheel": "unknown",
  "marching": "walk with",
  "bench pressing": "unkown",
  "deadlifting":"unknown", 
  "eating carrots": "eats with",
  "throwing discus": "unknown",
  "playing flute": "plays with",
  "cooking on campfire": "cooking",
  "breading on breadcrumbing": "unknown",
  "playing badminton": "plays with",
  "ripping paper": "unknown",
  "playing saxophone": "plays with",
  "milking cow": "unknown",
  "juggling balls": "unknown",
  "flying kite": "unknown",
  "capoeira":"unknown",
  "making jewelery":"unknown",
  "drinking":"drinking in a pub",
  "playing cymbals":"plays with",
  "cleaning gutters":"unknown",
  "hurling":"unknown",
  "playing organ": "plays with",
  "tossing coin":"unknown",
  "wrestling":"fights with",
  "driving car":"unknown",
  "headbutting":"fights with",
  "gymnastics tumbling":"unknown",
  "making bed":"unknown",
  "abseiling":"unknown",
  "holding snake":"unknown",
  "rock climbing":"unknown",
  "cooking egg":"cooking",
  "long jump": "unknown",
  "bee keeping": "unknown",
  "trimming or shaving beard": "unknown",
  "cleaning shoes": "unknown",
  "danging gangnam style": "dances with",
  "catching or throwing softball": "unknown",
  "ice skating": "unknown",
  "jogging": "runs to",
  "eating spaghetti": "eats with",
  "bobsledding": "unknown",
  "assembling computer": "unknown",
  "playing cricket": "plays with",
  "playing monopoly": "plays with",
  "golf putting": "plays with",
  "making pizza": "cooking",
  "javeling throw": "unknown",
  "peeling potatoes": "cooking",
  "clapping": "compliments",
  "brushing hair": "unknown",
  "flipping pancake": "cooking",
  "drinking beer": "drinking in a pub",
  "dribbling basketball": "plays with",
  "playing bagpipes": "plays with",
  "somersaulting": "unknown",
  "canoeing or kayaking": "unknown",
  "riding unicycle": "",

  
  


} 