

kinetics400_to_interaction ={ 
  "eating ice cream": "eats with",
  "marching": "walk with",
  "eating carrots": "eats with",
  "playing flute": "plays with",
  "cooking on campfire": "cooking",
  "playing badminton": "plays with",
  "playing saxophone": "plays with",
  "capoeira":"fights with",
  "drinking":"drinking in a pub",
  "playing cymbals":"plays with",
  "playing organ": "plays with",
  "wrestling":"fights with",
  "headbutting":"fights with",
  "cooking egg":"cooking",
  "trimming or shaving beard": "unknown",
  "cleaning shoes": "unknown",
  "danging gangnam style": "dances with",
  "jogging": "runs to",
  "eating spaghetti": "eats with",
  "playing cricket": "plays with",
  "playing monopoly": "plays with",
  "golf putting": "plays with",
  "making pizza": "cooking",
  "peeling potatoes": "cooking",
  "clapping": "compliments",
  "flipping pancake": "cooking",
  "drinking beer": "drinking in a pub",
  "dribbling basketball": "plays with",
  "playing bagpipes": "plays with",
  "texting": "write to",
  "tasting beer": "drinking in a pub",
  "playing clarinet": "plays with",
  "running on treadmill": "runs to",
  "tai chi": "fights with",
  "making sushi": "cooking",
  "playing kickball": "plays with",
  "headbanging": "dances with",
  "playing piano": "plays with",
  "dancing charleston": "dances with",
  "tickling" : "touches",
  "making a sandwich": "cooking",
  "cutting pineapple": "cooking",
  "dancing macarena": "dances with",
  "playing basketball": "plays with",
  "high kick": "fights with",
  "playing accordion": "plays with",
  "playing chess": "plays with",
  "jumpstyle dancing": "dances with",
  "writing": "write to",
  "sword fighting": "fights with",
  "playing poker": "plays with",
  "celebrating": "party",
  "playing squash or racquetball": "plays with",
  "belly dancing": "dances with",
  "playing trumpet": "plays with",
  "playing keyboard": "plays with",
  "playing controller": "plays with",
  "dodgeball": "plays with",
  "country line dancing": "dances with",
  "dancing ballet": "dances with",
  "cheerleading": "unknown", #could be dances with
  "eating watermelon": "eats with",
  "playing didgeridoo": "plays with",
  "eating doughnuts": "eats with",
  "drinking shots": "drinking at a pub",
  "playing ukulele": "plays with",
  "eating burger":"eats with",
  "applauding": "compliments",
  "hugging": "hugs",
  "massasing person's head": "touches",
  "eating hotdog": "eats with",
  "reading newspapers": "reads to",
  "zumba": "dances with",
  "playing ice hockey": "plays with",
  "breakdancing": "dances with",
  "robot dancing": "dances with",
  "playing paintball": "plays with",
  "massaging back": "touches",
  "playing violin": "plays with",
  "giving or receiving award": "gives gift to",
  "massaging legs": "touches",
  "salsa dancing": "dances with",
  "massaging feet": "touches",
  "playing drums": "plays with",
  "punching person": "fights with",
  "kissing": "kisses",
  "slapping": "fights with",
  "playing harmonica": "plays with",
  "cooking chicken": "cooking",
  "cooking sausages": "cooking",
  "playing xylophone": "plays with",
  "playing trombone": "plays with",
  "plyaing cello": "plays with",
  "making tea": "cooking",
  "playing tennis": "plays with",
  "crying": "crying",
  "dunking basketball": "plays with",
  "tasting food": "eats with",
  "eating chips": "eats with",
  "tap dancing": "dances with",
  "baking cookies": "cooking",
  "playing cards": "plays with",
  "playing bass guitar":"plays with",
  "walking with the dog" : "walks with",
  "tango dancing": "dances with",
  "side kick": "fights with",
  "eating cake": "eats with",
  "playing volleyball": "plays with",
  "swing dancing": "dances with",
  "playing guitar": "plays with",
  "playing harp": "plays with"
} 